#!/bin/bash
TMP=`mktemp`
cat > $TMP <<-tac
	import Control.Monad
	import Data.Array
	import Data.Bits
	import Data.Char
	import Data.Complex
	import Data.Int
	import Data.Ix
	import Data.List
	import Data.Maybe
	import Data.Ratio
	import Data.Word
	import Numeric
	import System.Environment
	import System.Exit
	import System.IO
	import System.IO.Error

	main = $*
tac
runghc $TMP
