#!/bin/bash

if (( $# < 2 )); then
    echo "Usage: `basename $0` COMMAND ARGS..." >&2
    exit 1
fi

for F in "${@:2}"; do
    echo -e "\e[1;33m====== $F ======\e[m"
    "$1" "$F" 2>&1
    echo
done
