#!/usr/bin/env python2

from __future__ import print_function
import sys
import os.path
import re
import os
import stat

if len(sys.argv) > 3:
    find, repl, files = sys.argv[1], sys.argv[2], sys.argv[3:]
elif len(sys.argv) == 3:
    find, repl, files = sys.argv[1], sys.argv[2], ['-']
else:
    name = os.path.basename(sys.argv[0])
    print('Usage: %s FIND REPL [FILES...]' % name, file=sys.stderr)
    exit(1)

rexp = re.compile(find, re.M)

for orig_name in files:
    if orig_name == '-':
        name = '/dev/stdin'
    elif not stat.S_ISREG(os.stat(orig_name).st_mode):
        print('Warning: ignoring non-regular file ' + orig_name,
            file=sys.stderr)
        continue
    else:
        name = orig_name
    
    with open(name, mode='r') as file:
        data = file.read()
    new_data = rexp.sub(repl, data)
    
    if orig_name == '-':
        name = '/dev/stdout'
    elif data != new_data:
        print('Changed: ' + name, file=sys.stderr)
    else:
        continue
    
    with open(name, mode='w') as file:
        file.write(new_data)
        file.flush()
