#!/usr/bin/env python2

from __future__ import print_function
import sys

lang = sys.argv[1] if len(sys.argv) > 1 else 'c'

if lang == 'c':
    print('/' + '*'*78 + '/')
elif lang == 'py':
    print('#' + '-'*79)
else:
    print('Error: "%s" is not a recognised language.' % lang, file=sys.stderr)
    sys.exit(1)
