# unattributed syntax highlighting example from wiki.linuxhelp.net/

syntax "makefile" "[Mm]akefile$"
color red "[:=]"
color magenta "\<(if|ifeq|else|endif)\>"
color blue "\$+[{(][a-zA-Z0-9_-]+[})]"
color brightblue "^[^ 	]+:"
color green "#.*$"
color ,red "^ +"
